apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.frontend.rule.type: PathPrefixStrip
  name: jeopardy
spec:
  rules:
  - host: raspberrypi
    http:
      paths:
      - backend:
          serviceName: jeopardy
          servicePort: 3000
        path: /jeopardy
  - host: audioboxer.onthewifi.com
    http:
      paths:
      - backend:
          serviceName: jeopardy
          servicePort: 3000
        path: /jeopardy
