apiVersion: skaffold/v1
kind: Config
metadata:
  name: jeopardy
build:
  artifacts:
  - image: seppler/jeopardy
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-service.yaml
    - k8s-ingress.yaml
